@echo off
cd /d "D:\OneDrive\Project\Claude\Nobi Skill\Nobi Skill"
echo Removing git lock...
if exist .git\index.lock del .git\index.lock
echo Adding files...
git add -A
echo Committing...
git commit -m "feat: age-based assessment + swipe-to-delete + AI analysis + compact cards"
echo Pushing...
git push
echo Done!
pause
